server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: microlink-api-gateway
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

# Link simulator configuration
link:
  simulator:
    command: ../link-sim/link_sim.exe  # Path to C simulator executable
    timeout: 5000

# Logging configuration
logging:
  level:
    com.microlink.api: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  server:
    port: 8081

# Application info
info:
  app:
    name: Microlink API Gateway
    description: Java API Gateway for Microwave Link Metrics
    version: 1.0.0
    author: Microlink Team 